apiVersion: v1
kind: Service
metadata:
  name: fcg-catalogs-service
  namespace: fcg-catalogs
spec:
  selector:
    app: fcg-catalogs
  ports:
    - protocol: TCP
      port: ${SERVICE_PORT}
      targetPort: ${CONTAINER_PORT}
  type: ClusterIP
